version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/documents:/app/documents       
      - ./backend/test.db:/app/test.db 
    environment:
      - DATABASE_URL=sqlite:///./test.db
    restart: always

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
